### ISSUE TITLE
Mean lines for filter replicates

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/COVID-19_WastewaterAnalysis#1]
Lines connecting the mean of the three qPCR replicates for one day to the next are misleading.  There's nothing in the protocol that links a sample labeled "filter replicate 1" on one day to another labeled "filter replicate 1" on another day.  Each daily sample is split into three filter replicates and then the replicates are arbitrarily numbered.

Suggestion for the plot:

- Base plot:   points with 9 values for each day, as we currently have.
- Toggle on:  Line connecting mean of all 9 samples for each day.
- Toggle on:  Points with means of 3 qPCR replicates for each day.  This point should be same color as each of the replicates, but distinguished by size or shape. 

What I see in my mind's eye:  When the mean line and mean points are toggled on, those are what pops out, and the 9 data points are less prominent.

**Comment by MarlinRLee** [comment]
Added The two toggles. Also added an error bar toggle option. I Attached some pictures of what they look like.
![LineOn](https://user-images.githubusercontent.com/76969165/113486325-beeaa580-9477-11eb-9024-7e7e2d3d46ab.png)
![LineMeanOn](https://user-images.githubusercontent.com/76969165/113486329-c27e2c80-9477-11eb-9ac2-4ba3f568c9a8.png)
![AllOn](https://user-images.githubusercontent.com/76969165/113486335-c5791d00-9477-11eb-9c33-22085b0b3276.png)
