### ISSUE TITLE
Date sliding

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/COVID-19_WastewaterAnalysis#14]
<img width="250" alt="shift_14" src="https://user-images.githubusercontent.com/7879996/118014724-21598000-b319-11eb-88d9-ed4d5412dfec.png">
<img width="250" alt="shift_7" src="https://user-images.githubusercontent.com/7879996/118014731-21f21680-b319-11eb-9320-cb8885aa578e.png">
<img width="250" alt="shift_0" src="https://user-images.githubusercontent.com/7879996/118014736-228aad00-b319-11eb-86b9-71abd5320566.png">
<img width="255" alt="shift_-7" src="https://user-images.githubusercontent.com/7879996/118014740-23234380-b319-11eb-8d3b-57ced42c0f47.png">
<img width="250" alt="shift_-14" src="https://user-images.githubusercontent.com/7879996/118014743-23bbda00-b319-11eb-948c-9bb3f1a089ac.png">

Here are screen shots with a range of date shifts.  Looking at any one of them individually, it's hard to discern what the trends are.  I think the window should be wide enough to accommodate the extreme on both ends without truncating.

**Comment by MarlinRLee** [comment]
The issue is that the case data covers a wider interval than the wastewater data. zooming out to get more of the case data pattern would either mean desyncing the x-axes or zooming out of both. When you zoom out of both the wastewater data looks scrunched.
![Examp](https://user-images.githubusercontent.com/76969165/118019701-e5291e00-b31e-11eb-8ff4-2c36076f66f4.PNG)

**Comment by SteveGoldstein** [comment]
Looks OK to me at this magnification.   You could increase the width of the panel so that the wastewater data remains the same size.

**Comment by SteveGoldstein** [comment]
Better but I'm craving a view that shows all the case data for the entire range of date shifts.

**Comment by MarlinRLee** [comment]
I pushed a version as wide as I think is reasonable to the beta version. zooming out anymore and most of the graphic will be empty data.
![Examp](https://user-images.githubusercontent.com/76969165/118024879-cf1e5c00-b324-11eb-9c55-1d73edfcdc53.PNG)

**Comment by SteveGoldstein** [comment]
Good enough for what I want to do with it for now.

Once we have more case data, I hope to be able to see trends.  I think this view will enable that.
