### ISSUE TITLE
Final dorm data

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/COVID-19_WastewaterAnalysis#18]
The dorm case data for the academic year is now in `results/2021-05-21`

**Comment by SteveGoldstein** [comment]
.. and I figure out the `git subtree` hoops to jump through!

**Comment by MarlinRLee** [comment]
When I pulled the change it has empty .tsv files.

**Comment by MarlinRLee** [comment]
![What I found](https://user-images.githubusercontent.com/76969165/119190118-895b4500-ba42-11eb-9d9c-2ffb7d3e5078.PNG)

**Comment by SteveGoldstein** [comment]
rats...   I ran the command and generated correct output as I was testing;  but then was careless when running the command to generate the output in the results/ dir.

It should be correct now.

**Comment by MarlinRLee** [comment]
updated the dorm data and pushed the change here: https://data-viz.it.wisc.edu/connect/#/apps/157/access. Will push it to the main one later.
